#-------------------------------
# General Site Settings

title: Lina Reid
description: Powered by Jekyll and GitHub Pages
email: lina.reid@telus.net

menu:
- {name: 'Home', url: 'index.html'}
- {name: 'Gallery', url: 'gallery.html'}
- {name: 'Resume', url: 'resume.html'}

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Personal portfolio powered by Jekyll and GitHub Pages '
  rel-author: 'https://plus.google.com/u/0/#'
  rel-publisher: 'https://plus.google.com/u/0/#'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

#google-analytics-ua: UA-XXXXXX-X

#-------------------------------
# About Section

about: >
  # Lina Reid

  <p>Hi! I'm Lina-- others may know me informally as Midna. I'm a concept artist whose passion is character and creature design! These past years have been spent honing my craft by doing daily practices, taking freelance commission work from clients both online and in person, and spending countless hours building whole worlds for my characters and creatures to reside in.</p>
  <p>Aside from being a dedicated artist, I am also a huge nerd. I love cartoons, comics, writing, world building, video games, furry, movies (especially horror!), sci-fi, and probably a ton of things I'm forgetting. Being passionate about a lot of things has created a deep pool for me to take inspiration from. I've even been fortunate enough to bring some of my wonderful creations (and other people's) to life in the form of costumes, and hopefully, eventually, in the form of my own video games.</p>

contact: >
  # Contact

  You may contact me [through my email](mailto:lina.reid@telus.net) or [tweet at me](https://twitter.com/Milksage) if you have any questions.

#-------------------------------
# Home Content
homeContent: >
  <p>Hi! I'm Lina-- others may know me informally as Midna. I'm a concept artist whose passion is character and creature design! These past years have been spent honing my craft by doing daily practices, taking freelance commission work from clients both online and in person, and spending countless hours building whole worlds for my characters and creatures to reside in.</p>
  <p>Aside from being a dedicated artist, I am also a huge nerd. I love cartoons, comics, writing, world building, video games, furry, movies (especially horror!), sci-fi, and probably a ton of things I'm forgetting. Being passionate about a lot of things has created a deep pool for me to take inspiration from. I've even been fortunate enough to bring some of my wonderful creations (and other people's) to life in the form of costumes, and hopefully, eventually, in the form of my own video games.</p><br>

#-------------------------------
# Featured title
portfolioTitle: >
  <hr>
  <h3>Portfolio</h3>

#-------------------------------
# Gallery
featuredTitle: >
  <h3>Featured Art</h3>
  <hr>

galleryTitle: >
  <h3>Gallery</h3>
  <hr>

#-------------------------------
# Work Section
projects:
- {name: 'Elliot Reference Sheet (Full) 2017', category: 'characters', folder: 'elliot', description: 'A reference sheet for Elliot Richards, the player character for a personal horror project that is underway. He&#39;s a fiesty, adventurous teenaged boy who will need to fight to survive. Reference features color swatches, expressions, and basic information for Elliot.'}
- {name: 'Exterior - Giovanni&#39;s', category: 'illustrations', folder: 'env2', description: 'Gritty section of a city, back door to some grody bar/club called Giovanni&#39;s. My imagining was something mafia related, and therefore the building may be a little underground.'}
- {name: 'Exterior - Ocean', category: 'illustrations', folder: 'env1', description: 'Something still in the works, inspired by Wind Waker, and Breath of the Wild-- both beautiful Legend of Zelda games.'}
- {name: 'Bunko', category: 'characters', folder: 'bunko', description: 'Reference sheet for a personal character, Bunko. Bunko is a Japanese fox demon known as a "kitsune", which are often known to play tricks and be very mischievous. Bunko got his name from the English word "bunco", which is a type of confidence trick-- an attempt to defraud someone after first allowing them to gain their confidence. Bunko is known to steal the life orbs of other Kitsune after winning rigged games that he sets up for them.'}
- {name: 'Bates Ref 2017', category: 'characters', folder: 'bates2', description: 'I started working on Bates in 2015, and figured it was time he got a full reference sheet. He is a cartoon character brought to life by scientists, who perhaps misunderstood the violent nature of cartoons upon doing so. What may be funny to a cartoon, and capable of a cartoon, may not translate well to real life...Bates is the main antagonist of a personal horror project I am currently working on; He is a apathetic, extremely intelligent monster who traps victims for his own playtime.'}
- {name: 'Bates Head', category: 'sketches', folder: 'bates', description: 'Turn-around reference for Bates&#39; head, as he has some odd shapes and atypical anatomy due to his being a cartoon brought to life.'}

#-------------------------------
# gallery
gallery:
- {file: 'dirty_looks_by_translucentrainbow-dbal0no.png', category: 'characters'}
- {file: 'djinni_by_translucentrainbow-daxcbik.png', category: 'characters'}
- {file: 'homework_wing_glider_by_translucentrainbow-darrmzr.jpg', category: 'illustrations'}
- {file: 'sama_art_trade_2_by_translucentrainbow-db8s5gp.png', category: 'illustrations'}
- {file: 'macaroni_new_ref_by_translucentrainbow-da14ck6.png', category: 'characters'}
- {file: 'schoolwork3_by_translucentrainbow-da6ulfl.jpg', category: 'characters'}
- {file: 'my_name_is_tsuki_i_secretly_have_a_boyfriend_who_i_by_translucentrainbow-d949l6q.png', category: 'characters'}
- {file: 'nostro_by_translucentrainbow-dal9bmx.png', category: 'characters'}
- {file: 'new_house-1.png', category: 'illustrations'}
- {file: 'pootoe_copy_by_translucentrainbow-d6p4rlm.png', category: 'illustrations'}
- {file: 'portfolio_piece1-1.png', category: 'illustrations'}
- {file: 'portfolio_piece2-2.png', category: 'illustrations'}
- {file: 'doki_new_ref_by_translucentrainbow-da0hg8m.png', category: 'characters'}
- {file: 'save_eli.png', category: 'illustrations'}
- {file: 'different_styles_2_by_translucentrainbow-d7944mf.png', category: 'sketches'}
- {file: 'serth_reference_2016_by_translucentrainbow-dacdswr.png', category: 'characters'}
- {file: 'shandor_reference_by_translucentrainbow-d93ebzo.png', category: 'characters'}
- {file: 'steven_sketches.png', category: 'sketches'}
- {file: 'roboo_copy_by_translucentrainbow-d767c81.png', category: 'sketches'}
- {file: 'stoler_new_ref.png', category: 'characters'}
- {file: '67jk56u4yg_by_translucentrainbow-d6lzhyx.png', category: 'illustrations'}
- {file: 'a_study_in_pink_by_translucentrainbow-d7kplop.png', category: 'illustrations'}
- {file: 'bates_u_r_scury3.png', category: 'illustrations'}
- {file: 'bike_drawing.png', category: 'illustrations'}
- {file: 'chibi_steve_by_translucentrainbow-d9dlut4.png', category: 'illustrations'}
- {file: 'creature_for_school.png', category: 'characters'}
- {file: 'cynic_reference_sheet.png', category: 'characters'}
- {file: 'different_styles_2_by_translucentrainbow-d7944mf.png', category: 'sketches'}
- {file: 'ed_die2.png', category: 'illustrations'}
- {file: 'eeeeeeeeeeeeeee.png', category: 'sketches'}
- {file: 'el_darling.png', category: 'sketches'}
- {file: 'emo.png', category: 'sketches'}
- {file: 'fabric_universe.jpg', category: 'illustrations'}
- {file: 'fat_orca_dragon_thing.png', category: 'sketches'}
- {file: 'frankiestein_by_translucentrainbow-d83ilwv.png', category: 'illustrations'}
- {file: 'i_hate_drawing_cats.png', category: 'characters'}
- {file: 'keka_commission.png', category: 'illustrations'}
- {file: 'mac_guro.png', category: 'illustrations'}
- {file: 'weimin_ref_by_translucentrainbow-d865amc.png', category: 'characters'}

#-------------------------------
# Resume Text
objective: >
  <h4>My objective:</h4>
  To gain employment in an entry-level position within a company that will utilize my skills and abilities, and provide opportunities for growth in a dynamic and stable workplace.

experiences: >
  <h3>Work Experiences</h3>
  <h4>Winners/Homesense&#58; Abbotsford, BC, Oct 2015 - Present</h4>
    <li>Running the till, stocking shelves, offloading the stock truck, customer service</li>
  <h4>Art Commissions&#58; Abbotsford, BC, 2010 – Present</h4>
    <li>Completed two murals, and have created my own business in which clients can contact me and request character designs, drawings, sketches, etc</li>

volunteer: >
  <h3>Volunteer Experience</h3>
  <h4>Abbotsford Arts Council&#58; Abbotsford, BC, 2013 – 2015</h4>
    <li>Gallery Attendant</li>
    <li>Running the cash till</li>
    <li>Computerized record keeping</li>
    <li>Greeting visitors</li>
    <li>general office duties</li>
  <h4>MSA Museum Society&#58; Abbotsford, BC, 2009 – Present</h4>
    <li>Planning and execution of special events at Tretheway House Heritage Site including set-up, and tear down as well as general office duties</li>
    <li>Creating graphic art for press releases and published works</li>

skills: >
  <h3>Skills and Abilities</h3>
  <li>Well versed in Adobe Photoshop; I employ Photoshop regularly for all my artwork, which includes character design, illustration, portraits, commissions, photo manipulation, as well as to create business cards and posters.</li>
  <li>I have advanced knowledge using Windows operating systems, and a base knowledge using Mac operating systems.</li>
  <li>I have applied basic skills in HTML/CSS coding and web design.</li>
  <li>Knowledgeable in multiple computer programs including Adobe Photoshop, Correl Painter, Audacity, Open Office, and Word.</li>
  <li>A published artist who applies my skills in a variety of mediums successfully including drawing, watercolors, acrylics, and in the use of the Wacom Intuos tablet for digital painting and sketching.</li>
  <li>I am a skilled writer and have produced works which exceeded 100,000 words.</li>

education: >
  <h3>Education</h3>
  <h4>Vancouver Animation School&#58; 2014 – March 2017</h4>
    <li>Concept Art Diploma</li>
  <h4>Yale Secondary School&#58; 2009 – 2013</h4>
    <li>Graduated Grade 12, consistently on Honor Roll, average 90%</li>

awards: >
  <h3>Awards and Achievements</h3>
  <li>A 10% Scholarship at the Vancouver Animation School in 2014</li>
  <li>Outstanding Achievement and four years of Honor Roll at Yale Secondary School</li>
  <li>Arty Awards nominee for Outstanding Emerging Artist from Abbotsford Art Council in 2010</li>

#-------------------------------
# Contact Section

social:
- {icon: 'twitter', link: 'https://twitter.com/Milksage'}
- {icon: 'youtube', link: 'https://www.youtube.com/channel/UCZ-x9fZMzniKj0Ibu72OhcQ'}

# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
